apiVersion: v1
kind: Namespace
metadata:
  name: k8s-api-coverage
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: apicoverage-webhook
  namespace: k8s-api-coverage
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: apicoverage-webhook-role
rules:
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["validatingwebhookconfigurations"]
  verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: apicoverage-webhook-clusterrolebinding
  namespace: k8s-api-coverage
subjects:
- kind: ServiceAccount
  name: apicoverage-webhook
  namespace: k8s-api-coverage
roleRef:
  kind: ClusterRole
  name: apicoverage-webhook-role
  apiGroup: rbac.authorization.k8s.io
